// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"mall/user/rpc/internal/logic"
	"mall/user/rpc/internal/svc"
	"mall/user/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.IdRequest) (*user.UserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) FindUserLike(ctx context.Context, in *user.UserLikeRequest) (*user.UserLikeResponse, error) {
	l := logic.NewFindUserLikeLogic(ctx, s.svcCtx)
	return l.FindUserLike(in)
}
